# A simple ubuntu with tools and non root user
FROM ubuntu:24.04

# Install the tools and create the ubuntu user
RUN apt update && apt install -y vim curl git jq apache2-utils dnsutils traceroute

# Switch to ubuntu user and /home/ubuntu working directory
USER ubuntu
WORKDIR /home/ubuntu
