apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artifactory-load.fullname" . }}-run-script
  labels:
    app: {{ template "artifactory-load.name" . }}
    chart: {{ template "artifactory-load.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  run.sh: |
{{ .Files.Get "files/run.sh" | indent 4 }}
