{{ if .Values.deployment3.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "artifactory-load.fullname" . }}-3
  labels:
    app: {{ template "artifactory-load.name" . }}
    chart: {{ template "artifactory-load.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment3.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "artifactory-load.name" . }}
      chart: {{ template "artifactory-load.chart" . }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "artifactory-load.name" . }}
        chart: {{ template "artifactory-load.chart" . }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "artifactory-load.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - exec /home/ubuntu/run.sh
          env:
            - name: ARTIFACTORY_URL
              value: "{{ .Values.artifactory.url }}"
            - name: ARTIFACTORY_USER
              value: "{{ .Values.artifactory.user }}"
            - name: ARTIFACTORY_PASSWORD
              value: "{{ .Values.artifactory.password }}"
            - name: FILE
              value: "{{ .Values.deployment3.file }}"
            - name: AUTH
              value: "{{ .Values.artifactory.auth }}"
            - name: REQUESTS
              value: "{{ .Values.deployment3.requests }}"
            - name: CONCURRENCY
              value: "{{ .Values.deployment3.concurrency }}"
            - name: INFINITE
              value: "{{ .Values.infinite }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: run-script
              mountPath: "/home/ubuntu/run.sh"
              subPath: "run.sh"
      volumes:
        - name: run-script
          configMap:
            name: {{ include "artifactory-load.fullname" . }}-run-script
            defaultMode: 0774
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
